plugin: aws_ec2

regions:
  - ap-northeast-2

filters:
  instance-state-name: running
#  instance-type: "{{ aws_instance_type }}"
  tag:aws:autoscaling:groupName: minecraft

hostnames:
  - network-interface.association.public-ip
