plugin: aws_ec2
regions:
  - ap-northeast-2
filters:
  instance-state-name: running
#  instance-type: "{{ aws_instance_type }}"
  tag:aws:autoscaling:groupName: minecraft

hostnames:
  - network-interface.association.public-ip
all:
  hosts:
    localhost:
      vars:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
